/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package libgoutil/Libs/goutil */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "goutil.go"

#include <stdint.h>
#include <stdlib.h>

typedef void (*http_handler_fn)(uintptr_t ctx_id);
typedef const char cchar_t;

static inline void call_swift_handler(http_handler_fn fn, uintptr_t ctx_id) {
    fn(ctx_id);
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern char* StartServer(char* port);
extern void EPrint(cchar_t* msg);
extern void Print(cchar_t* msg);
extern void NewRoute(char* path, http_handler_fn handler);
extern void* GetRequestID(uintptr_t ctxID);
extern void* GetResponseID(uintptr_t ctxID);
extern int HttpWrite(void* ctxID, char* data, int length);
extern void HttpWriteHeader(void* ctxID, int statusCode);
extern void HttpSetHeader(void* ctxID, char* key, char* value);
extern void HttpAddHeader(void* ctxID, char* key, char* value);
extern void HttpDelHeader(void* ctxID, char* key);
extern char* HttpGetHeader(void* ctxID, char* key);
extern char* ReqGetMethod(void* ctxID);
extern char* ReqGetURL(void* ctxID);
extern char* ReqGetPath(void* ctxID);
extern char* ReqGetRawQuery(void* ctxID);
extern char* ReqGetQuery(void* ctxID, char* key);
extern char* ReqGetHeader(void* ctxID, char* key);
extern char* ReqGetHost(void* ctxID);
extern char* ReqGetRemoteAddr(void* ctxID);
extern char* ReqGetProto(void* ctxID);
extern int64_t ReqGetContentLength(void* ctxID);
extern int ReqReadBody(void* ctxID, char* buffer, int length);
extern char* ReqReadBodyFull(void* ctxID, int* outLen);
extern char* ReqGetCookie(void* ctxID, char* name);
extern char* ReqGetUserAgent(void* ctxID);
extern char* ReqGetReferer(void* ctxID);
extern void HttpSetCookie(void* ctxID, char* name, char* value, char* path, int maxAge);

#ifdef __cplusplus
}
#endif
